# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Binary

concurrency: production

on:
  push:
    branches:
      - master
    #tags:
    #  - 'v[0-9]+.[0-9]+.[0-9]+'           # Push events to every tag not containing /

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: ${{ github.ref }}
        run: bash .github/scripts/create_release.sh
